### ISSUE TITLE
Unhandled Exceptions

### ISSUE THREAD

**Issue by fuzzyfurry069** [fr-Pursuit/AsiSupport#9]
I've got a lot of unhandled exceptions when trying to open TrainerV/Simper Trainer after switching to it from NativeTrainer.

Attached is my RPH log from my latest attempt at using TrainerV/Simple Trainer
[TrainerV/Simper Trainer](https://www.gta5-mods.com/scripts/simple-trainer-for-gtav)

[RagePluginHook.log](https://github.com/fr-Pursuit/AsiSupport/files/8617877/RagePluginHook.log)

**Comment by fr-Pursuit** [comment]
Hello,

Based on your logs, it appears that the unhandled exception originated from LSPDFR. Since there is no evidence linking it to AsiSupport nor TrainerV, I'm afraid I cannot assist you further.

LSPDFR is a notoriously stable plugin, so another plugin/script is probably causing it to crash. TrainerV, by itself, should also work fine with ASI Support since, from what I know, sjaak327 is using it to test his script on new GTA V versions.

To troubleshoot your issue, you can try removing scripts and / or plugins from your game to see if there's any improvements. You can also try to disable specific functions from your trainer(s) to see if they can cause instabilities with LSPDFR. Your logs indicate LSPDFR is trying to work with an invalid Ped, so you can start by removing scripts/functions that involve despawning peds.

For more assistance, you can try to seek help on the [RAGE Plugin Hook Discord server](https://discord.gg/z8N5P9MCRx
). The support people out there are great!

**Comment by fuzzyfurry069** [comment]
I hear that, the biggest reason why I sent this is was that I was opening my native trainer and it all broke and hard crashed after trying. I still appreciate the response and I will give that a try. Have a great day!
